// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Výstava {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  gallery: string;
  start_date: string;
  end_date: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Galerie {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  address: string;
  web?: string;
  note?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Stránka {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    exhibitions: Výstava;
    galleries: Galerie;
    pages: Stránka;
  }
}